os: linux
language: php

# services:
#   - docker

before_install:
  # https://github.com/containers/libpod/blob/master/install.md#ubuntu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman

  # Show version and info.
  - podman --version
  - podman version
  - podman info --debug
  - apt-cache show podman
  - dpkg-query -L podman

  # Hack podman's configuration files.
  # /etc/containers/registries.conf does not exist.
  # https://clouding.io/kb/en/how-to-install-and-use-podman-on-ubuntu-18-04/
  - ls -1 /etc/containers/registries.conf || true
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf

before_script:
  - podman build --no-cache -t outrise/webapp_podman:${TRAVIS_COMMIT} .
  # - docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /go/src/github.com/kainlite/whatismyip-go/whatismyip-go.test
  - podman run -d -p 127.0.0.1:80:80 outrise/webapp_podman:${TRAVIS_COMMIT}
  - podman ps -a

script:
  - curl 127.0.0.1:80
  - echo "$DOCKER_PASSWORD" | podman login -u "$DOCKER_USERNAME" --password-stdin
  - podman push outrise/webapp_podman:${TRAVIS_COMMIT}

notifications: true
